### ISSUE TITLE
training data 

### ISSUE THREAD

**Issue by YYingcute** [xiaoyufenfei/LEDNet#20]
could you tell me how to convert the dataset to 19 categories.I just use the *_color.png picture for training ,but after some step,it will report an error.
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1535490206202/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:266
/opt/conda/conda-bld/pytorch_1535490206202/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [1,0,0], thread: [160,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by xiaoyufenfei** [comment]
Hi, please use the scripts for preparing the Cityscapes Dataset https://github.com/mcordts/cityscapesScripts

**Comment by Benjiaminh** [comment]
> could you tell me how to convert the dataset to 19 categories.I just use the *_color.png picture for training ,but after some step,it will report an error.
> RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1535490206202/work/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:266
> /opt/conda/conda-bld/pytorch_1535490206202/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [1,0,0], thread: [160,0,0] Assertion `t >= 0 && t < n_classes` failed.

你解决了这个问题吗，我也忘了要用这个了。。。请问集解决了，如果解决了可以告诉我怎么解决的吗
